// The A3 as Markdown, rendered from the model alone (Anchor, harnesses and A3, section 5.1).
import type { A3Model } from "./types.ts";

export const UNWRITTEN = "Not yet written.";
const pct = (x: number) => `${Math.round(x * 100)}%`;
// Judgment text is data: a "<" is escaped so that no raw HTML reaches a viewer, and a backtick never opens a code span.
const md = (s: string) => s.replaceAll("<", "\\<");
const code = (s: string) => (s.includes("`") ? md(s) : `\`${s}\``);
const row = (cells: string[]) => `| ${cells.map((c) => md(c).replaceAll("|", "\\|").replaceAll("\n", " ")).join(" | ")} |`;
const or = (s: string) => (s.trim() === "" ? `_${UNWRITTEN}_` : s);

export function authorityLine(m: A3Model): string {
  if (m.authority.authority === "approved") return `approved${m.authority.selfApproved ? " (self-approved)" : ""}`;
  return `candidate${m.authority.reason !== undefined ? ` (${m.authority.reason})` : ""}: the judgments are not approved`;
}

const stageName = (st: { id: string; name: string }) => (st.name.trim() === "" ? st.id : st.name);

export function renderMarkdown(m: A3Model): string {
  const out: string[] = [];
  const stages = m.stages;
  const first = stages[0];
  const label = (stage: number, id: string) => stages[stage]?.signals.find((s) => s.id === id)?.label ?? id;
  out.push(`# A3: ${m.title.trim() === "" ? UNWRITTEN : md(m.title)}`, "");
  out.push(`Generated by \`csh a3 build ${m.slug}\` from the stage records in \`stages/\` and the judgments in \`judgments.json\`; edit those, not this file. The same sheet as a page, with a picker for each stage, is [a3.html](a3.html).`, "");
  out.push(`**Component.** ${md(m.component)}. **Authority.** ${authorityLine(m)}. **Judgments.** \`${m.judgmentsDigest}\`.`, "");
  out.push(`**Problem.** ${md(or(m.problem))}`, "");

  out.push("## The run, stage by stage", "");
  if (stages.length === 0) out.push("No stage records.", "");
  else {
    out.push(row(["Stage", "What happens", "Tests", "Signals", "Conflicts", "Rules satisfied", "Gate"]), row(["---", "---", "---:", "---:", "---:", "---:", "---"]));
    for (const st of stages) out.push(row([stageName(st), or(st.what), `${st.tests.passed} of ${st.tests.total}`, String(st.signals.length), String(st.conflicts), `${st.rules.filter((r) => r.verdict === "satisfied").length} of ${st.rules.length}`, `${st.gate.overall} (${st.gate.mode})`]));
    out.push("");
  }

  out.push("## 1. Background", "", ...(m.background.length === 0 ? [`_${UNWRITTEN}_`] : m.background.flatMap((p) => [md(p), ""])));
  if (m.background.length === 0) out.push("");
  if (m.practices.length > 0) {
    out.push(row(["", ...m.practices.map((p) => p.name)]), row(["---", ...m.practices.map(() => "---")]));
    out.push(row(["Kind", ...m.practices.map((p) => p.kind)]));
    out.push(row(["Author", ...m.practices.map((p) => p.author ?? "")]));
    out.push(row(["One artefact", ...m.practices.map((p) => p.unit ?? "")]));
    out.push(row(["Sources", ...m.practices.map((p) => p.sources.join(", "))]));
    out.push(row(["Cannot say", ...m.practices.map((p) => p.cannotSay ?? UNWRITTEN)]), "");
  }

  out.push("## 2. Current condition", "");
  if (first !== undefined) {
    out.push(`At the first stage, ${first.signals.length} signals.`, "");
    if (m.decisionPoints.length === 0) out.push(`Decision points: _${UNWRITTEN}_`, "");
    else {
      out.push("What each practice says at each decision point, and what CSH reports:", "");
      out.push(row(["Decision point", ...m.practices.map((p) => p.name), "CSH reports", "Class"]), row(["---", ...m.practices.map(() => "---"), "---", "---"]));
      for (const d of m.decisionPoints) {
        const hits = (d.signals[0] ?? []).map((id) => label(0, id));
        out.push(row([d.point, ...m.practices.map((p) => d.says[p.id]?.text ?? "silent"), hits.join("; ") || "no signal", d.class]));
      }
      out.push("");
    }
    out.push("Where the signals were injected, by lane:", "");
    for (const l of m.lanes) out.push(`- ${md(l.title)} (${code(l.where)}): ${l.counts[0] ?? 0}`);
    if (m.lanes.length === 0) out.push(`- _${UNWRITTEN}_`);
    out.push("", "Pareto of the signals by cause:", "", row(["Cause", "n", "Cumulative", "Vital few"]), row(["---", "---:", "---:", "---"]));
    for (const b of m.pareto[0]?.bars ?? []) out.push(row([b.name, String(b.n), pct(b.cumulative), b.vital ? "yes" : ""]));
    out.push("", `Every signal at the first stage (${first.signals.length}):`, "");
    for (const s of first.signals) out.push(`- ${md(s.label)}${s.cause === undefined ? " (unclassified)" : ""}`);
    out.push("");
  } else out.push("No stage records.", "");

  out.push("## 3. Goal", "", md(or(m.goal)), "");
  if (stages.length > 0) {
    out.push(row(["Measure", "Target", ...stages.map(stageName)]), row(["---", "---:", ...stages.map(() => "---:")]));
    for (const x of m.measures) out.push(row([x.name, x.target, ...x.values.map((v) => `${v.value}${v.met ? " ✓" : ""}`)]));
    out.push("");
  }

  const ev = (e: A3Model["rca"][number]["evidence"]) => (e === undefined ? "" : ` Evidence: ${"finding" in e ? `finding ${md(e.finding)} at stage ${md(e.stage)}` : `"${md(e.text)}" in ${code(e.file)}`}${e.resolves ? "" : " (dangling)"}.`);
  out.push("## 4. Root cause analysis", "");
  if (m.rca.length === 0) out.push(`_${UNWRITTEN}_`);
  m.rca.forEach((q) => out.push(`- **${md(q.id)}. ${md(q.q)}** ${md(q.a)}${ev(q.evidence)} ${md(q.depth)}`));
  out.push("", "### The 5 Whys", "");
  if (m.whys.length === 0) out.push(`_${UNWRITTEN}_`);
  m.whys.forEach((w, i) => out.push(`${i + 1}. **${md(w.q)}** ${md(w.a)}${ev(w.evidence)}`));
  const root = m.whys.find((w) => w.root !== undefined);
  if (root !== undefined) out.push("", md(root.root!));
  out.push("");

  out.push("## 5. Countermeasures", "", "To the system, never to a person. Status is computed from the stage records.", "");
  if (m.countermeasures.length === 0) out.push(`_${UNWRITTEN}_`);
  else {
    out.push(row(["#", "Kind", "Countermeasure", "Answers", "Status"]), row(["---", "---", "---", "---", "---"]));
    for (const c of m.countermeasures) out.push(row([c.id, c.kind, c.what, c.answers.join(" "), c.status]));
  }
  out.push("", "## 6. Plan", "");
  if (m.plan.length === 0) out.push(`_${UNWRITTEN}_`);
  else out.push(row(["What", "Who", "When"]), row(["---", "---", "---"]), ...m.plan.map((p) => row([p.what, p.who, p.when])));

  out.push("", "## 7. Follow-up", "", `At the last stage the ${m.followUp.gate.mode} gate says ${m.followUp.gate.overall}.${m.followUp.returned.length > 0 ? ` Signals that went away and came back: ${md(m.followUp.returned.join("; "))}.` : ""}`, "");
  const names = [...new Set(stages.flatMap((s) => s.rules.map((r) => r.name)))].sort();
  if (names.length > 0) {
    out.push("The rules at each stage, as the gate sees them:", "", row(["Rule", ...stages.map(stageName)]), row(["---", ...stages.map(() => "---")]));
    for (const name of names) out.push(row([`\`${name}\``, ...stages.map((s) => { const r = s.rules.find((x) => x.name === name); return r ? `${r.verdict}, ${r.authority}${r.disposition !== "candidate" ? `, ${r.disposition}` : ""}` : "absent"; })]));
    out.push("");
  }

  if (m.terms.length > 0) out.push("## Terms", "", ...m.terms.map((t) => `- **${md(t.term)}**: ${md(t.meaning)}`), "");
  out.push("## Problems with the judgments", "");
  if (m.problems.length === 0) out.push("None.");
  for (const p of m.problems) out.push(`- \`${p.kind}\`${p.stage !== undefined ? ` at ${p.stage}` : ""}: ${md(p.subject)}. ${md(p.detail)}.`);
  out.push("");
  return out.join("\n");
}
